name: Eslint + Typescript+ Testing FE

on: push

runs:
  using: composite
  steps:

    - name: Install Node.js dependencies
      shell: bash
      working-directory: frontend
      run: npm ci

    - name: Run build
      shell: bash
      working-directory: frontend
      run: CI=false npm run build --if-present  

    - name: Run eslint
      shell: bash
      working-directory: frontend
      run: npm run eslint

    - name: Run typescript
      shell: bash
      working-directory: frontend
      run: npm run typecheck

    - name: Run tests
      shell: bash
      working-directory: frontend
      run: npm run test
